import { ModelProviderCard } from '@/types/llm';

// refs to: https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
const OpenAI: ModelProviderCard = {
  chatModels: [
    {
      description:
        'GPT 3.5 Turbo, suitable for a variety of text generation and understanding tasks',
      displayName: 'GPT-3.5 Turbo',
      functionCall: true,
      id: 'gpt-3.5-turbo',
      price: '€0.95',
      private: true,
      tokens: 16_385,
    },
    {
      displayName: 'GPT-3.5 Turbo (0125)',
      functionCall: true,
      hidden: true,
      id: 'gpt-3.5-turbo-0125',
      tokens: 16_385,
    },
    {
      displayName: 'GPT-3.5 Turbo (1106)',
      functionCall: true,
      hidden: true,
      id: 'gpt-3.5-turbo-1106',
      tokens: 16_385,
    },
    {
      displayName: 'GPT-3.5 Turbo Instruct',
      hidden: true,
      id: 'gpt-3.5-turbo-instruct',
      tokens: 4096,
    },
    {
      displayName: 'GPT-3.5 Turbo 16K',
      hidden: true,
      id: 'gpt-3.5-turbo-16k',
      tokens: 16_385,
    },
    {
      displayName: 'GPT-3.5 Turbo (0613)',
      hidden: true,
      id: 'gpt-3.5-turbo-0613',
      legacy: true,
      tokens: 4096,
    },
    {
      displayName: 'GPT-3.5 Turbo 16K (0613)',
      hidden: true,
      id: 'gpt-3.5-turbo-16k-0613',
      legacy: true,
      tokens: 4096,
    },
    {
      displayName: 'GPT-4 Turbo Preview',
      functionCall: true,
      id: 'gpt-4-turbo-preview',
      price: '€19.0',
      private: true,
      tokens: 128_000,
    },
    {
      displayName: 'GPT-4 Turbo Preview (0125)',
      functionCall: true,
      hidden: true,
      id: 'gpt-4-0125-preview',
      tokens: 128_000,
    },
    {
      description: 'GPT-4 visual preview version, supporting visual tasks',
      displayName: 'GPT-4 Turbo Vision Preview',
      hidden: true,
      id: 'gpt-4-vision-preview',
      price: '€19.0',
      private: true,
      tokens: 128_000,
      vision: true,
    },
    {
      displayName: 'GPT-4 Turbo Preview (1106)',
      functionCall: true,
      hidden: true,
      id: 'gpt-4-1106-preview',
      tokens: 128_000,
    },
    {
      displayName: 'GPT-4',
      functionCall: true,
      hidden: true,
      id: 'gpt-4',
      tokens: 8192,
    },
    {
      displayName: 'GPT-4 (0613)',
      functionCall: true,
      hidden: true,
      id: 'gpt-4-0613',
      tokens: 8192,
    },
    {
      displayName: 'GPT-4 32K',
      functionCall: true,
      hidden: true,
      id: 'gpt-4-32k',
      tokens: 32_768,
    },
    {
      displayName: 'GPT-4 32K (0613)',
      functionCall: true,
      hidden: true,
      id: 'gpt-4-32k-0613',
      tokens: 32_768,
    },
    {
      displayName: 'GPT-4 ALL',
      files: true,
      functionCall: true,
      hidden: true,
      id: 'gpt-4-all',
      tokens: 32_768,
      vision: true,
    },
    {
      description: 'Currently points to gpt-4o-2024-05-13',
      displayName: 'GPT-4o',
      functionCall: true,
      id: 'gpt-4o',
      price: '~9€',
      private: true,
      tokens: 128_000,
      vision: true,
    },
  ],
  enabled: true,
  id: 'openai',
};

export default OpenAI;
